-- Club Student Database schema for Supabase Free.
-- Run this once in the Supabase SQL Editor.
-- Intentionally excludes club status, interests, project teams, equipment,
-- achievements, certificates, QR cards, and member task tracking.

create extension if not exists pgcrypto;

create table if not exists public.students (
  student_id text primary key,
  full_name text not null,
  class text,
  section text,
  roll integer,
  date_of_birth date,
  gender text,
  student_contact_number text,
  email_address text,
  home_address text,
  guardians_name text,
  relationship_to_student text,
  guardians_contact_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists students_class_section_idx on public.students (class, section);
create index if not exists students_full_name_idx on public.students (full_name);

create table if not exists public.batches (
  id uuid primary key default gen_random_uuid(),
  batch_number integer generated by default as identity unique,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.batch_students (
  batch_id uuid not null references public.batches(id) on delete cascade,
  student_id text not null references public.students(student_id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (batch_id, student_id)
);
create index if not exists batch_students_student_idx on public.batch_students (student_id);

-- Specific committee/volunteer appointments. The ADM001-linked Supabase user
-- is the only account allowed to change these assignments.
create table if not exists public.committee_positions (
  student_id text primary key references public.students(student_id) on delete cascade,
  position text not null check (position in (
    'President', 'Vice President', 'General Secretary', 'Joint Secretary', 'Treasurer',
    'Organizing Secretary', 'IT Secretary', 'Publicity Secretary', 'Executive Member',
    'Volunteer Coordinator', 'Event Volunteer', 'Technical Volunteer', 'Content Volunteer'
  )),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

-- Private authorization link, synced from the email saved on student ADM001
-- to the matching Supabase Auth account when this schema runs.
create table if not exists public.committee_role_managers (
  student_id text primary key check (student_id = 'ADM001'),
  user_id uuid not null references auth.users(id) on delete cascade,
  manager_email text not null,
  linked_at timestamptz not null default now()
);
alter table public.committee_role_managers enable row level security;
revoke all on public.committee_role_managers from anon, authenticated;

insert into public.committee_role_managers (student_id, user_id, manager_email, linked_at)
select 'ADM001', account.id, lower(trim(account.email)), now()
from public.students as student
join auth.users as account on lower(trim(account.email)) = lower(trim(student.email_address))
where student.student_id = 'ADM001'
  and nullif(trim(student.email_address), '') is not null
on conflict (student_id) do update
set user_id = excluded.user_id,
    manager_email = excluded.manager_email,
    linked_at = excluded.linked_at;

create or replace function public.is_committee_role_manager()
returns boolean
language sql
stable
security definer
set search_path = ''
as $body$
  select exists (
    select 1 from public.committee_role_managers as manager
    where manager.student_id = 'ADM001' and manager.user_id = auth.uid()
  );
$body$;
revoke all on function public.is_committee_role_manager() from public, anon, authenticated;
grant execute on function public.is_committee_role_manager() to authenticated;

create table if not exists public.batch_resources (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references public.batches(id) on delete cascade,
  category text not null check (category in ('material', 'announcement')),
  title text not null check (length(trim(title)) between 1 and 160),
  body text not null default '',
  file_name text,
  object_path text unique,
  content_type text,
  file_size bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (file_size is null or (file_size > 0 and file_size <= 26214400)),
  check (
    (object_path is null and file_name is null and content_type is null and file_size is null)
    or (object_path is not null and file_name is not null and content_type is not null and file_size is not null)
  ),
  check (category <> 'announcement' or content_type is null or content_type = 'application/pdf'),
  check (category <> 'announcement' or length(trim(body)) > 0 or object_path is not null)
);
-- Materials can now be written as full text articles; attachments are optional.
do $migration$
declare old_constraint record;
begin
  for old_constraint in
    select conname from pg_constraint
    where conrelid = 'public.batch_resources'::regclass
      and contype = 'c'
      and conname <> 'batch_resources_material_body_or_file_check'
      and lower(pg_get_constraintdef(oid)) like '%category <> ''material''%'
      and lower(pg_get_constraintdef(oid)) like '%object_path is not null%'
  loop
    execute format('alter table public.batch_resources drop constraint %I', old_constraint.conname);
  end loop;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.batch_resources'::regclass
      and conname = 'batch_resources_material_body_or_file_check'
  ) then
    alter table public.batch_resources
      add constraint batch_resources_material_body_or_file_check
      check (category <> 'material' or object_path is not null or length(trim(body)) > 0);
  end if;
end;
$migration$;
create index if not exists batch_resources_batch_created_idx on public.batch_resources (batch_id, created_at desc);
create index if not exists batch_resources_category_idx on public.batch_resources (category);

create table if not exists public.attendance_sessions (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  session_date date not null,
  batch_id uuid references public.batches(id) on delete restrict,
  created_at timestamptz not null default now()
);
alter table public.attendance_sessions add column if not exists batch_id uuid references public.batches(id) on delete restrict;
create index if not exists attendance_sessions_batch_idx on public.attendance_sessions (batch_id);
create index if not exists attendance_sessions_date_idx on public.attendance_sessions (session_date desc);

create table if not exists public.attendance_records (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.attendance_sessions(id) on delete cascade,
  student_id text not null references public.students(student_id) on delete cascade,
  status text not null check (status in ('Present', 'Absent', 'Late')),
  created_at timestamptz not null default now(),
  unique (session_id, student_id)
);
create index if not exists attendance_records_student_idx on public.attendance_records (student_id);
create index if not exists attendance_records_session_idx on public.attendance_records (session_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $body$
begin
  new.updated_at = now();
  return new;
end;
$body$;
drop trigger if exists students_set_updated_at on public.students;
create trigger students_set_updated_at before update on public.students
for each row execute function public.set_updated_at();
drop trigger if exists batch_resources_set_updated_at on public.batch_resources;
create trigger batch_resources_set_updated_at before update on public.batch_resources
for each row execute function public.set_updated_at();

alter table public.students enable row level security;
alter table public.batches enable row level security;
alter table public.batch_students enable row level security;
alter table public.committee_positions enable row level security;
alter table public.batch_resources enable row level security;
alter table public.attendance_sessions enable row level security;
alter table public.attendance_records enable row level security;
revoke all on public.students from anon, authenticated;
revoke all on public.batches from anon, authenticated;
revoke all on public.batch_students from anon, authenticated;
revoke all on public.committee_positions from anon, authenticated;
revoke all on public.batch_resources from anon, authenticated;
revoke all on public.attendance_sessions from anon, authenticated;
revoke all on public.attendance_records from anon, authenticated;
grant select, insert, update, delete on public.students to authenticated;
grant select, insert, update, delete on public.batches to authenticated;
grant select, insert, update, delete on public.batch_students to authenticated;
grant select, insert, update, delete on public.committee_positions to authenticated;
grant select, insert, update, delete on public.batch_resources to authenticated;
grant usage, select on sequence public.batches_batch_number_seq to authenticated;
revoke all on sequence public.batches_batch_number_seq from anon;
grant select, insert, update, delete on public.attendance_sessions to authenticated;
grant select, insert, update, delete on public.attendance_records to authenticated;

drop policy if exists "Admins manage students" on public.students;
create policy "Admins manage students" on public.students for all to authenticated
using (auth.uid() is not null) with check (auth.uid() is not null);
drop policy if exists "Admins manage batches" on public.batches;
create policy "Admins manage batches" on public.batches for all to authenticated
using (auth.uid() is not null) with check (auth.uid() is not null);
drop policy if exists "Admins manage batch students" on public.batch_students;
create policy "Admins manage batch students" on public.batch_students for all to authenticated
using (auth.uid() is not null) with check (auth.uid() is not null);
drop policy if exists "ADM001 reads committee positions" on public.committee_positions;
create policy "ADM001 reads committee positions" on public.committee_positions for select to authenticated
using (public.is_committee_role_manager());
drop policy if exists "ADM001 manages committee positions" on public.committee_positions;
create policy "ADM001 manages committee positions" on public.committee_positions for all to authenticated
using (public.is_committee_role_manager()) with check (public.is_committee_role_manager());
drop policy if exists "Admins manage batch resources" on public.batch_resources;
create policy "Admins manage batch resources" on public.batch_resources for all to authenticated
using (auth.uid() is not null) with check (auth.uid() is not null);
drop policy if exists "Admins manage attendance sessions" on public.attendance_sessions;
create policy "Admins manage attendance sessions" on public.attendance_sessions for all to authenticated
using (auth.uid() is not null) with check (auth.uid() is not null);
drop policy if exists "Admins manage attendance records" on public.attendance_records;
create policy "Admins manage attendance records" on public.attendance_records for all to authenticated
using (auth.uid() is not null) with check (auth.uid() is not null);

-- The student portal uses these narrow public RPCs instead of reading the
-- private student, membership, or resource tables directly.
create or replace function public.get_public_batches()
returns table (
  batch_id uuid,
  batch_number integer,
  batch_name text,
  student_id text,
  full_name text
)
language sql
stable
security definer
set search_path = ''
as $body$
  select b.id, b.batch_number, b.name, s.student_id, s.full_name
  from public.batches as b
  left join public.batch_students as bs on bs.batch_id = b.id
  left join public.students as s on s.student_id = bs.student_id
  order by b.batch_number, s.student_id nulls last;
$body$;
revoke all on function public.get_public_batches() from public, anon, authenticated;
grant execute on function public.get_public_batches() to anon, authenticated;

create or replace function public.get_public_batch_resources()
returns table (
  id uuid,
  batch_id uuid,
  batch_number integer,
  batch_name text,
  category text,
  title text,
  body text,
  file_name text,
  object_path text,
  content_type text,
  file_size bigint,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $body$
  select r.id, r.batch_id, b.batch_number, b.name, r.category, r.title,
         r.body, r.file_name, r.object_path, r.content_type, r.file_size, r.created_at
  from public.batch_resources as r
  join public.batches as b on b.id = r.batch_id
  order by r.created_at desc, r.title;
$body$;
revoke all on function public.get_public_batch_resources() from public, anon, authenticated;
grant execute on function public.get_public_batch_resources() to anon, authenticated;

-- Published files are intentionally public. Mutations stay behind the same
-- signed-in administrator role used by the private admin panel.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'club-materials', 'club-materials', true, 26214400,
  array[
    'application/pdf', 'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/plain', 'text/csv', 'application/zip',
    'image/jpeg', 'image/png', 'image/webp'
  ]
)
on conflict (id) do update set
  name = excluded.name,
  public = true,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins manage club materials" on storage.objects;
create policy "Admins manage club materials" on storage.objects
for all to authenticated
using (bucket_id = 'club-materials' and auth.uid() is not null)
with check (bucket_id = 'club-materials' and auth.uid() is not null);
